### ISSUE TITLE
Compatibilty with other creeper-like mods

### ISSUE THREAD

**Issue by PssbleTrngle** [team-abnormals/savage-and-ravage#124]
Currently the code tests wether or not the exploding entity is of the type `minecraft:creeper`  ([code](https://github.com/team-abnormals/savage-and-ravage/blob/ab48ae7ba2bbe804bc2ccb7983d314f5ff4e5e14/src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java#L194)).
Instead, it could test for a new entity tag (`savage_and_ravage:creeper_like`) and a `instanceof Creeper` check.

This would allow compatibility with mods like Overhauled Creepers using a datapack

**Comment by bageldotjpg** [comment]
Going to pass on these PRs for 2 reasons:
1) This is intentional; Creepies only look like the vanilla Creeper and are meant to only come from the vanilla Creeper. Sometimes different modded creepers have different reactions upon exploding and we don't want to overwrite that.
2) We do not currently plan to support 1.18.2 any further
