### ISSUE TITLE
A crash related to ImprovedCrossbowGoal

### ISSUE THREAD

**Issue by noncom** [team-abnormals/savage-and-ravage#133]
There is a crash related to `ImprovedCrossbowGoal` occurring in interop with other mods.

Log: https://gist.github.com/noncom/1d968db181f0250894a579026e1c84ce 

Long story short, please take a look at https://github.com/TelepathicGrunt/Bumblezone/issues/201 where the comment https://github.com/TelepathicGrunt/Bumblezone/issues/201#issuecomment-1407516378 explains the problem and the solution.

**Comment by Vaelzan** [comment]
I've been seeing quite a few null pointer exceptions in all sorts of pieces of code related to the ImprovedCrossbowGoal.

There's this issue report here too: https://github.com/team-abnormals/savage-and-ravage/issues/120

As well as people now getting disconnected in Valhelsia 5 with this: https://gist.github.com/Vaelzan/a996d28d6b13e00eec18da022db9e14f

(the NBT data that it's erroring on is the crossbow owner tag)

I have no idea if it's the same root cause, as I haven't been able to investigate anywhere near as thoroughly as I was hoping (due to illness). Some null safety checks would help (in the case of the disconnection that I've been seeing, at least), but I don't think they'll resolve the issue of *why* things are null in the first place.

**Comment by zeid0ne** [comment]
I still have the bug https://bytebin.lucko.me/lgkOIKFze8
Is it planned to be fixed ?

thanks for all
