### ISSUE TITLE
Mods that disable DataFixerUpper cause the S&R outpost to not spawn.

### ISSUE THREAD

**Issue by BugmanBugman** [team-abnormals/savage-and-ravage#57]
For some reason, the disabling of DFU causes that specific structure to not spawn. Try it with datafixslayer, or enable the DFU option in random patches. Doing so will cause the  S&R outpost to not spawn, but you'll still be able to locate it. It's very odd.

**Comment by bageldotjpg** [comment]
This is probably better suited to reported for those mods because Savage & Ravage doesn't add a new structure it simply replaces the old one with just a simple nbt file so this seems like it would affect more than Savage & ravage

**Comment by Vaelzan** [comment]
I've messaged Bagel on Discord, but here too just in case... this is caused by the NBT that Savage and Ravage uses being from an older version of Minecraft. It should be fixed in Savage and Ravage so that it doesn't need to get run through the DataFixerUpper in the first place, which will improve performance as well as resolve the bug.
