### ISSUE TITLE
[Suggestion] Separate option to allow burning banners to start a raid

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/savage-and-ravage#64]
It would be nice to be able to set the "Illagers no longer give Bad Omen when killed" option to false and still be able to burn ominous banners to start a raid.

**Comment by abigailfails** [comment]
I don't really want to add this to the config file since it's confusing balance-wise - if the player turns both options off they can't get raids at all, and if they're both on you get twice as many opportunities to increase your bad omen level. What's your intended use for this? Either way, you could make a mod that re-adds bad omen on death using events to fulfil the purpose of a config option.

**Comment by MarioSMB** [comment]
For what it's worth, Terraria offers both methods to start a goblin raid; you can craft their banner *and* get encounters randomly, it offers more control to the player to be able to start a raid when they want to and not rely on random events, but without completely removing the illager encounters.  
We found it very confusing to not be able to burn banners to trigger a raid, as it's a core feature of this mod.
